### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Changyu-Guo** [qq2856237457/jianshu#1]
我使用 `git clone https://github.com/qq2856237457/jianshu.git` 下载了项目

并且 `cd ./jianshu`

然后使用 `yarn install` 安装了依赖

接下来执行了 `yarn start`

但是得到了如下的错误：

**Failed to compile**
```
./src/store/reducer.js
Module not found: Can't resolve 'redux-immutable' in 'E:\jianshu\src\store'
This error occurred during the build time and cannot be dismissed.
```

**Comment by Kobe-G** [comment]
一定要注意工程的规范啊

**Comment by qq2856237457** [comment]
redux-immutable没有安装，我的本地目录里面的redux-immutable是安装工程目录的上一层目录里面的

**Comment by qq2856237457** [comment]
> 一定要注意工程的规范啊
见谅，我第一次使用github

**Comment by Changyu-Guo** [comment]
> redux-immutable没有安装，我的本地目录里面的redux-immutable是安装工程目录的上一层目录里面的

我通过执行 `yarn add redux-immutable` 安装了 `redux immutable package`

并再次执行 `yarn start` 成功启动了项目

项目非常不错，运用了 `React` 的众多相关技术，说明你已经对 `React` 有了一定的掌握

但是对于一个初学者来说，应该尽可能少的利用你不了解的库，例如 `create-react-app` 和 `immutable.js` 等

另外，你的项目使用了 `redux-thunk middleware`，你应该思考一下，你的项目为什么需要 `redux-thunk`，假如没有 `redux-thunk`，你的 `action creator` 应该如何写，相较于使用了 `redux-thunk`，缺陷在哪。

接下来希望你能针对项目做如下的改进：

1. 在此项目的基础上，新建一个 **分支** 进行修改
2. 取消使用 `create-react-app`，自己使用 `webpack` 等 `package` 搭建环境
3. 针对 `src/pages/home` 页面（仅此一个页面），尝试取消使用 `redux-thunk middleware` 来派发请求

**Comment by qq2856237457** [comment]
是的 我会在后续的学习中继续进行项目的改进，谢谢建议
